controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\services\ElasticClient;
use Yii;
use yii\caching\DbDependency;
use yii\caching\TagDependency;
use yii\db\Expression;
use yii\filters\HttpCache;
use yii\filters\PageCache;
use yii\web\Controller;
use yii\web\Response;
use app\models\ContactForm;

class SiteController extends Controller
{
    private \Elasticsearch\Client $client;

    public function __construct($id, $module, $config = [])
    {
        $this->client = (new ElasticClient())->client;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex()
    {
        $query = Yii::$app->request->get('query');
        $start = microtime(true);
        $docs = [];
        if ($query) {
            $params = [
                'index' => 'products',
                'size' => 1000,
                'body' => [
                    'query' => [
                        'match' => [
                            'description' => $query
                        ]
                    ]
                ]
            ];
            $response = $this->client->search($params);

            $docs = ($response['hits']['hits']); // documents
        }
        $end = microtime(true);
        $spend = round(($end - $start)*1000).'ms';

        return $this->render('elastic', [
            'docs' => $docs,
            'query' => $query,
            'spend' => $spend
        ]);
    }

    public function actionPostgres()
    {
        $query = Yii::$app->request->get('query');
        $start = microtime(true);
        $docs = [];
        if ($query) {
            $docs = Product::find()
                ->select([
                    'name',
                    'description',
                    new Expression("ts_headline('russian', description, plainto_tsquery('russian','$query'),'StartSel=<em>, StopSel=</em>, MaxFragments=0, MinWords=5, MaxWords=9') as query"),
                    'created_at',
                    new Expression("document <=> plainto_tsquery('russian','$query') as distance")
                ])
                ->where(new Expression("document @@ plainto_tsquery('russian','$query')"))
                // RUM index ishlatilgan. Buni desc berib bolmaydi
                ->orderBy(new Expression("document <=> plainto_tsquery('russian','$query')"))
                ->limit(1000)
                ->asArray()
                ->all();
        }
//debug($docs);
        $end = microtime(true);
        $spend = round(($end - $start)*1000).'ms';

        return $this->render('postgres', [
            'docs' => $docs,
            'query' => $query,
            'spend' => $spend
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/catalog.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */
?>

<?php $this->beginContent('@app/views/layouts/layout.php')?>
<div class="row">
<!-- ФРАГМЕНТНИ КЕШЛАШ -->
    <div class="col-lg-2 col-md-2 col-sm-12">
        <?php if ($this->beginCache("side-bar-widget",
            [
                'dependency'=> [
                    'class' => \yii\caching\TagDependency::class,
                    'tags' => [\app\repositories\IncomeGoodRepository::allTagDependency(), \app\repositories\SaleGoodRepository::allTagDependency()]
                ],
                'duration'=>3600,
                'variations'=> $action.$good_id
        ]
        )) :?>
        <?php echo \app\widgets\SideBarWidget::widget();
            ?>
        <?php $this->endCache(); endif; ?>
    </div>
    <div class="col-lg-10 col-md-10 col-sm-12">
        <?= $content ?>
    </div>
</div>
<?php $this->endContent()?>

views/layouts/layout.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Elastic', 'url' => ['/site/index']],
            ['label' => 'Postgres Full text search', 'url' => ['/site/postgres']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container" style="width: 90%">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <div class="row">

            <?= $content ?>
        </div>

    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Search research <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */
?>

<?php $this->beginContent('@app/views/layouts/layout.php')?>
<?= $content ?>
<?php $this->endContent()?>